export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
export const USER_LOGOUT = "USER_LOGOUT";
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";
export const GET_ONE_USER = "GET_ONE_USER";
export const GET_ONE_USER_SUCCESS = "GET_ONE_USER_SUCCESS";
export const GET_ONE_USER_ERROR = "GET_ONE_USER_ERROR";
export const UPDATE_ONE_USER = "UPDATE_ONE_USER";
export const UPDATE_ONE_USER_SUCCESS = "UPDATE_ONE_USER_SUCCESS";
export const UPDATE_ONE_USER_ERROR = "UPDATE_ONE_USER_ERROR";
export const SET_GETONEUSERID = "SET_GETONEUSERID";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_ALL_ROLES_ERROR = "GET_ALL_ROLES_ERROR";
export const BYPASSLOGIN = "BYPASSLOGIN";
export const CHANGEOWNPASSWORD = "CHANGEOWNPASSWORD"

export const CHANGEOWNPASSWORD_ERROR = "CHANGEOWNPASSWORD_ERROR"
export const RESETUSERPASSWORD = "RESETUSERPASSWORD";
export const RESETUSERPASSWORD_ERROR = "RESETUSERPASSWORD_ERROR";
//the bypasslogin method lets you become the admin if you are creating your account for the first time.
